spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      enabled: false
  rabbitmq:
    host: rabbitmq
    port: 5672

queues:
  busyBooksQueue: busyBooksQueue
  bookIdQueue: bookIdQueue
  busyBooksRequestQueue: busyBooksRequestQueue

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html