spring.datasource.url=jdbc:postgresql://localhost:5433/record_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

queues.busyBooksQueue=busyBooksQueue
queues.bookIdQueue=bookIdQueue
queues.busyBooksRequestQueue=busyBooksRequestQueue